[Definition]

actionstart = iptables -N FAIL2BAN 2>/dev/null || true
              iptables -I INPUT -j FAIL2BAN 2>/dev/null || true

actionstop = iptables -D INPUT -j FAIL2BAN 2>/dev/null || true
             iptables -F FAIL2BAN 2>/dev/null || true
             iptables -X FAIL2BAN 2>/dev/null || true

actionban = iptables -I FAIL2BAN 1 -s <ip> -j LOG --log-prefix "FAIL2BAN-BLOCK: " --log-level 4
            iptables -I FAIL2BAN 2 -s <ip> -j DROP

actionunban = iptables -D FAIL2BAN -s <ip> -j LOG 2>/dev/null || true
              iptables -D FAIL2BAN -s <ip> -j DROP 2>/dev/null || true

[Init]





















# Действия при запуске fail2ban
#actionstart = iptables -N FAIL2BAN 2>/dev/null || true
#              iptables -I INPUT -j FAIL2BAN 2>/dev/null || true

# Действия при остановке fail2ban
#actionstop = iptables -D INPUT -j FAIL2BAN 2>/dev/null || true
#             iptables -F FAIL2BAN 2>/dev/null || true
#             iptables -X FAIL2BAN 2>/dev/null || true

# 3. При бане IP (логируем и блокируем)
#actionban = iptables -I FAIL2BAN 1 -s <ip> -j LOG --log-prefix "FAIL2BAN-BLOCK: " --log-level 4
#            iptables -I FAIL2BAN 2 -s <ip> -j DROP

# 4. При разбане IP (удаляем оба правила)
#actionunban = iptables -D FAIL2BAN -s <ip> -j LOG 2>/dev/null || true
#              iptables -D FAIL2BAN -s <ip> -j DROP 2>/dev/null || true




# Действия при бане
#actionban = iptables -I FAIL2BAN 1 -s <ip> -j DROP

# Действия при разбане
#actionunban = iptables -D FAIL2BAN -s <ip> -j DROP 2>/dev/null || true
